export const PagesNames = {
  Home: 'Home',
  InitPage: 'InitPage',
  RegisterStep1: 'RegisterStep1',
  RegisterStep2: 'RegisterStep2',
  RegisterStep3: 'RegisterStep3',
  RegisterStep4: 'RegisterStep4',
  Login: 'Login',
  RecoveryStep1: 'RecoveryStep1',
  RecoveryStep2: 'RecoveryStep2',
  RecoveryStep3: 'RecoveryStep3',
  OnBoarding: 'OnBoarding',
  Loading: 'Loading',
  ProfileCreationStep1: 'ProfileCreationStep1',
  ProfileCreationStep2: 'ProfileCreationStep2',
  ProfileCreationStep3: 'ProfileCreationStep3',
  ProfileCreationStep4: 'ProfileCreationStep4',
};
