export default {
  fontFamily: {
    GeologicaBlack: 'Geologica-Black',
    GeologicaBlackItalic: 'Geologica-BlackItalic',
    GeologicaBold: 'Geologica-Bold',
    GeologicaBoldItalic: 'Geologica-BoldItalic',
    GeologicaExtraBold: 'Geologica-ExtraBold',
    GeologicaExtraBoldItalic: 'Geologica-ExtraBoldItalic',
    GeologicaExtraLight: 'Geologica-ExtraLight',
    GeologicaExtraLightItalic: 'Geologica-ExtraLightItalic',
    GeologicaItalic: 'Geologica-Italic',
    GeologicaLight: 'Geologica-Light',
    GeologicaLightItalic: 'Geologica-LightItalic',
    GeologicaMedium: 'Geologica-Medium',
    GeologicaMediumItalic: 'Geologica-MediumItalic',
    GeologicaRegular: 'Geologica-Regular',
    GeologicaSemiBold: 'Geologica-SemiBold',
    GeologicaSemiBoldItalic: 'Geologica-SemiBoldItalic',
    GeologicaThin: 'Geologica-Thin',
    GeologicaThinItalic: 'Geologica-ThinItalic',
    GeologicaCRSVSHRPslntwght: 'GeologicaCRSVSHRPslntwght',
    TekturBlack: 'Tektur-Black',
    TekturBold: 'Tektur-Bold',
    TekturExtraBold: 'Tektur-ExtraBold',
    TekturMedium: 'Tektur-Medium',
    TekturRegular: 'Tektur-Regular',
    TekturSemiBold: 'Tektur-SemiBold',
  },
  fontSize: {
    web: {
      header1: 48,
      header2: 38,
      header3: 34,
      header4: 28,
      header6: 21,
      subTitle1: 18,
      subTitle2: 16,
      subTitle3: 14,
      m: 16,
      s: 14,
      l: 18,
      xs: 13,
      ButtonLarge: 21,
      ButtonMedium: 16,
      ButtonSmall: 14,
      Caption1: 12,
      Caption2: {
        fontSize: 10,
        fontWeight: '700',
      },
      caption3: 10,
      caption4: 8,
    },
    mobile: {
      header1: 32,
      header2: 28,
      header3: 26,
      header4: 17,
      header6: 14,
      subTitle1: 15,
      subTitle2: 14,
      subTitle3: 13,
      m: 14,
      s: 13,
      l: 16,
      xs: 12,
      ButtonLarge: 20,
      ButtonMedium: 16,
      ButtonSmall: 14,
      Caption1: 11,
      Caption2: {
        fontSize: 10,
        fontWeight: '500',
      },
      caption3: 10,
      caption4: 8,
    },
  },
};
